name: CI/CD

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        id: login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          file: apps/client/Dockerfile
          push: true
          tags: ${{ secrets.CLIENT_DOCKER_IMAGE }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          file: apps/server/Dockerfile
          push: true
          tags: ${{ secrets.SERVER_DOCKER_IMAGE }}

      - name: Docker Logout
        if: always()
        run: docker logout ${{ steps.login.outputs.registry }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy docker-compose
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/Portfolio"

      - name: Docker Login
        id: login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Put environment variables and run containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Portfolio/
            touch .env
            echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PG_URL=${{ secrets.PG_URL }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "CLIENT_DOCKER_IMAGE=${{ secrets.CLIENT_DOCKER_IMAGE }}" >> .env
            echo "SERVER_DOCKER_IMAGE=${{ secrets.SERVER_DOCKER_IMAGE }}" >> .env
            docker kill client server && docker rm client server
            docker rmi ${{ secrets.CLIENT_DOCKER_IMAGE }}
            docker rmi ${{ secrets.SERVER_DOCKER_IMAGE }}
            docker-compose up -d
            cd .. && rm -rf Portfolio

      - name: Docker Logout
        if: always()
        run: docker logout ${{ steps.login.outputs.registry }}
